"""
Generate a Stage 7 sessions config (stage7_real_run.py --sessions-config) for every
inherited-homography lane, from the products built for them -- never by hand:

  homography      homography_calibration_inherited_corrected/<stem>_homography.json
                  (per-lane translation-corrected, visually validated)
  sync_result     thermalFeatures/trajectory_sync/session_sync_results.json
                  (trajectory alignment, per session, visually QC'd)
  entry time      <retrack-dir>/retrack_start_frames.csv thermal_entry_sec
                  (RGB entry detection + entry_time_overrides.csv; the same value the
                  lane's re-tracking started from)
  tracking_csv    <retrack-dir>/trackingOutputs/<stem>_tracking_every10frames.csv
  bouts_csv       split out of <retrack-dir>/retrack/bout_table.csv into per-lane
                  <bouts-out-dir>/<stem>_bout_rows.csv (same columns as compute_bouts.py's
                  per-file sidecar, which Stage 7 reads)
  seq / video     re-rooted from the homography JSON's recorded paths
  mouse_id        from <retrack-dir>/retrack/metadata_join_report.csv (the LUT join the main analysis
                  uses), so Stage 7 and the analysis always agree. The ID parsed from the session label
                  (<id>_F / <id>_B) is only a cross-check: where it differs, the entry carries
                  mouse_id_filename + mouse_id_note (e.g. 08-19-25 Test9, whose LUT row notes the .seq
                  name is wrong; 07-31-25 Test4-009, where LUT and filename disagree on F/B).

The human-verified stage7_sessions_config.json (Test_3/4/7) is never touched; those
sessions are skipped here even if present.

Paths in the output are relative to --repo-dir, as stage7_real_run.py resolves them.

Usage (run where the re-track outputs live, e.g. inside slurm/run_stage7_inherited.sbatch):
    python scripts/build_stage7_inherited_config.py --retrack-dir thermalFeatures/retrack_2026-10 \\
        --output thermalFeatures/stage7_inherited/stage7_sessions_config_inherited.json \\
        --bouts-out-dir thermalFeatures/stage7_inherited/bouts
"""

import argparse
import json
import re
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent
LANE_NAMES = {"F": "Front", "B": "Back"}


def mouse_id_for_lane(session_label: str, lane: str) -> int:
    hits = re.findall(r"(\d{4})_([FB])(?=_|$)", session_label)
    ids = [int(i) for i, l in hits if l == lane]
    if len(ids) != 1:
        raise ValueError(f"cannot parse lane {lane} mouse id from {session_label!r}")
    return ids[0]


def main():
    parser = argparse.ArgumentParser(description="Build Stage 7 config for inherited-homography lanes")
    parser.add_argument("--repo-dir", default=str(REPO))
    parser.add_argument("--retrack-dir", default="thermalFeatures/retrack_2026-10",
                        help="Repo-relative re-track run dir (trackingOutputs/, retrack/, retrack_start_frames.csv)")
    parser.add_argument("--homography-dir", default="homography_calibration_inherited_corrected")
    parser.add_argument("--sync-json", default="thermalFeatures/trajectory_sync/session_sync_results.json")
    parser.add_argument("--bouts-out-dir", default="thermalFeatures/stage7_inherited/bouts")
    parser.add_argument("--output", default="thermalFeatures/stage7_inherited/stage7_sessions_config_inherited.json")
    args = parser.parse_args()

    repo = Path(args.repo_dir)
    rel = lambda p: str(Path(p))  # keep repo-relative strings as given
    human = {e["session_label"] for k, e in json.load(open(repo / "stage7_sessions_config.json")).items()
             if not k.startswith("_")}
    sync = json.load(open(repo / args.sync_json))
    starts = pd.read_csv(repo / args.retrack_dir / "retrack_start_frames.csv").set_index("seq_stem")
    bout_table = pd.read_csv(repo / args.retrack_dir / "retrack" / "bout_table.csv")
    joined = pd.read_csv(repo / args.retrack_dir / "retrack" / "metadata_join_report.csv")
    lut_mouse = {(r.stem, r.lane): int(r.mouse_id) for r in joined.itertuples() if pd.notna(r.mouse_id)}
    (repo / args.bouts_out_dir).mkdir(parents=True, exist_ok=True)
    (repo / args.output).parent.mkdir(parents=True, exist_ok=True)

    config = {"_comment": (
        "GENERATED by scripts/build_stage7_inherited_config.py -- do not edit by hand. Stage 7 config for "
        "the inherited-homography lanes: corrected homography, trajectory-alignment sync, RGB-detected "
        "entry time, re-tracked tracking + bouts. See that script's docstring for each field's source.")}
    problems = []
    for hj in sorted((repo / args.homography_dir).glob("*_homography.json")):
        meta = json.load(open(hj))
        stem = hj.name.replace("_homography.json", "")
        session, lane = stem.rsplit("_", 1)[0], meta["lane"]
        if session in human:
            continue
        if session not in sync:
            problems.append(f"{stem}: no session sync")
            continue
        if stem not in starts.index:
            problems.append(f"{stem}: no entry time / start frame")
            continue
        if (session, lane) not in lut_mouse:
            problems.append(f"{stem}: no metadata-join mouse_id")
            continue
        mouse_id, mouse_id_filename = lut_mouse[(session, lane)], mouse_id_for_lane(session, lane)
        bouts = bout_table[bout_table.video_file == f"{stem}.seq"]
        bouts_rel = f"{args.bouts_out_dir}/{stem}_bout_rows.csv"
        bouts.to_csv(repo / bouts_rel, index=False)
        sr = {k: sync[session][k] for k in ("offset_sec", "drift_slope", "r_squared", "residual_max_sec",
                                            "low_confidence", "confidence_note")}
        s = starts.loc[stem]
        config[f"{session}_{lane}"] = dict(
            session_label=session,
            thermal_seq_relpath=meta["seq_path"].split("/croppedSeqFiles/", 1)[1],
            rgb_video_relpath=meta["video_path"].split("/Process_Jason/", 1)[1],
            homography_json=rel(hj.relative_to(repo)),
            tracking_csv=f"{args.retrack_dir}/trackingOutputs/{stem}_tracking_every10frames.csv",
            bouts_csv=bouts_rel,
            mouse_id=mouse_id,
            track=lane,
            entry_time_thermal_sec=float(s.thermal_entry_sec),
            entry_time_note=(f"RGB entry detection (scripts/detect_entry_rgb.py)"
                             + (", manual override (entry_time_overrides.csv)" if bool(s.overridden) else "")
                             + (", via other lane's handling episode" if bool(s.entry_via_other_lane) else "")
                             + f"; tracking re-started at frame {int(s.start_frame)}"),
            sync_result=sr,
            n_bouts=len(bouts),
        )
        if mouse_id != mouse_id_filename:
            config[f"{session}_{lane}"].update(
                mouse_id_filename=mouse_id_filename,
                mouse_id_note="mouse_id from the LUT metadata join; the session filename says otherwise")
            problems.append(f"{stem}: LUT mouse {mouse_id} != filename mouse {mouse_id_filename} (LUT used)")
    with open(repo / args.output, "w") as f:
        json.dump(config, f, indent=2)
    print(f"{len(config) - 1} lanes -> {args.output}; per-lane bouts -> {args.bouts_out_dir}")
    if problems:
        print("NOTES / SKIPPED:", *problems, sep="\n  ")


if __name__ == "__main__":
    main()
